print("Hello world!")
print()
print('Скоро я','буду','программировать на Python!')
print()
print('1', '2', '4', '9', '16')
print()
print('В тексте есть двойные кавычки ""')
print()
print("В тексте есть одинарные '' кавычки ")
#print('Как тебя зовут?')
name = input('Как тебя зовут?')
print('Привет,', name)